#!/usr/bin/env bash
# This script installs and configures Nginx on an Ubuntu server.

# Update the package list
sudo apt-get update -y

# Install Nginx
sudo apt-get install nginx -y

# Create a custom HTML file for the root page
echo "Holberton School for the win!" | sudo tee /var/www/html/index.html > /dev/null

#Test configuration
sudo nginx -t || { echo "Nginx configuration error"; exit 1; }

# Restart Nginx without using systemctl
sudo service nginx restart
