#!/usr/bin/env bash
# Configure Nginx to redirect /redirect_me to a new location
cat <<EOF | sudo tee /etc/nginx/sites-available/default > /dev/null
server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/html;
    index index.html index.htm;

    server_name _;

    location / {
        try_files \$uri \$uri/ =404;
    }

    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }
}
EOF

# Test the Nginx configuration
if ! sudo nginx -t; then
	echo "Nginx configuration test failed. Check the configuration file."
	exit 1
fi

# Restart Nginx to apply the changes
if ! sudo service nginx restart; then
	echo "Failed to restart Nginx. Check the logs for errors."
fi

# Verify the redirection
if ! curl -sI localhost/redirect_me | grep -q "301 Moved Permanently"; then
    echo "Redirection test failed. Check the Nginx configuration."
    exit 1
fi

echo "Redirection configured successfully."
