#!/usr/bin/env bash
sudo apt-get update -y
sudo apt-get install nginx -y

sudo tee /etc/nginx/sites-available/default > /dev/null <<'EOF'
server {
    listen 80;
    server_name _;

    location ~ ^/redirect_me(/.*)?$ {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }

    location / {
        root /var/www/html;
        index index.html; }
}
EOF

sudo nginx -t && sudo service nginx restart

